### ISSUE TITLE
storing machines in .dot files

### ISSUE THREAD

**Issue by fstonedahl** [ddarmon/transCSSR#1]
I noticed that you seem to be using the .dot file to store the machine, not just for visualization, but also for later re-loading it (`load_transition_matrix_machine`) to perform simulations with it.

However, when you save .dot files, you're only using three decimal points of precision... (presumably because labeling edges with 0.192838813423 looks messy).  However, this feels like it introduces a needless  (albeit small) amount of error into your simulations.  For transitions with very small values, I think the error could be significant...

Also, while parsing the .dot files works, it feels kludgy.  Could you instead write the full data describing the epsilon machine to a simpler file format that is purely used for persistence/serialization, not visualization?

Ideally, I think it would be nice to have a data structure that stores the epsilon machine transition data, and just pass that into a "save_dot_file" function or a "save_machine_matrix_file" function, etc.

_Note: I started looking at this because I'm currently meeting with Bill, and we were discussing the possibility of taking the output from transCSSR and simulating the resulting epsilon machines in other languages.  This would be simpler if the machines were saved in a more straightforward way than .dot format... and it would be a more precise representation if it included the full numeric value rather than 3 decimal places._

**Comment by aariyaratne** [comment]
Last time I discussed precision with dave, understanding we come to is that probabilities loose any meaning after 4th decimal place. Hence that value is chosen not only for visualization purposes, they are meaningless after 4th place. That means we will be using very expensive doubles for no reason. 

I have a function to generate JSON files as an alternative to .dot files. Let me know if you want it.

**Comment by ghost** [comment]
Last time I discussed precision with dave, understanding we come to is that probabilities loose any meaning after 4th decimal place. Hence that value is chosen not only for visualization purposes, they are meaningless after 4th place. That means we will be using very expensive doubles for no reason if the precision is extended.

I have a function to generate JSON files as an alternative to .dot files. Let me know if you want it.

**Comment by fstonedahl** [comment]
Hmm, I see.  I would think that the precision of probabilities would be dependent on the amount of data that was fed into CSSR, and that for some datasets higher precision might be possible.

And yes, I would be interested in seeing your JSON-generating code - you should be able to attach a file to a comment on this thread...

**Comment by ddarmon** [comment]
Hi Forrest,

Good point! I never worked from the dot files myself, since I always went straight from inference to using the model and didn't usually rely on a saved dot file.

As Arjuna mentioned, the variance in the estimator for the probabilities overwhelms any apparent precision in the probabilities. And as you noted, that will depend on the amount of data and the particularities of the stochastic process. For example, for a Markov chain, the estimator for the transition probability from state i to state j has approximate variance (p_{ij} (1 - p_{ij}))/N_{i}, so the standard deviation of the estimator will go down something like 1 / sqrt(N). You could use this as a rough estimate of the actual precision in your estimates based on the length of your time series. I recommend Guttorp's *Stochastic Modeling of Scientific Data* for more details on the sampling properties of estimators for Markov chains.

The .dat_results files may be more what you're looking for. Those contain the transition structure, as well as transition probabilities to 12 or so decimal places.

As a short term solution, you can change the lines like:

> wfile.write('{} -> {} [label = \"{}|{}:{:.3}\"];\n'.format(numeric_to_alpha(printing_lookup[state]), numeric_to_alpha(printing_lookup[to_state]), ay, ax, prob_by_state[state][len(ays)*input_lookup[ax] + output_lookup[ay]]))

in the draw_dot* functions so that the {:.3} is whatever level of assumed precision you want. e.g. 10 decimal places would be {:.10}, etc.

I wrote the output files to match Cosma Shalizi's CSSR outputs, since that is the only other eM reconstruction algorithm publicly available.

It sounds like Arjuna's JSON solution may be exactly what you're looking for.

**Comment by fstonedahl** [comment]
Arjuna -- can you attach the JSON-generating code?

**Comment by aariyaratne** [comment]
Unfortunately, I can't seem to find the code in my working laptop (Old one died). However, I remember that writing that code was a trivial task. As I remember, I modified draw_dot function to output JSON.

**Comment by ghost** [comment]
Unfortunately, I can't seem to find the code in my working laptop (Old one died). However, I remember that writing that code was a trivial task. As I remember, I modified draw_dot function to output JSON.
